version: '3.9'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: ${WORKING_DIR}
        volumes:
            - '.:${WORKING_DIR}'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${PORT_WEB}:80'

    php-fpm:
        build: "${PHP_PFM}"
        working_dir: ${WORKING_DIR}
        volumes:
            - '.:${WORKING_DIR}'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
